otatools: build-with-colors
- add new file for common functions and stuff
 - though it doesn't contain any function now ;)
- red color for errors
- yellow color for "Optimizing: *"
- cyan color for modversion :)
- green color for "package complete"
- and some general cleanup

Change-Id: I83b2e352580e99b1766c5e63821281224cde5c49

based on the github commit by Chirayu Desai committed to cm

diff --git a/tools/squisher b/tools/squisher
--- a/tools/squisher
+++ b/tools/squisher
@@ -1,8 +1,10 @@
-#!/bin/sh
+#!/bin/bash
 #
 # Squish a CM otapackage for distribution
 # cyanogen
 #
+
+. $ANDROID_BUILD_TOP/vendor/baked/tools/functions
 
 OUT_TARGET_HOST=`uname -a | grep Darwin`
 if [ -z "$OUT_TARGET_HOST" ]
@@ -19,8 +21,8 @@ else
 fi
 
 if [ -z "$OUT" -o ! -d "$OUT" ]; then
-    echo "ERROR: $0 only works with a full build environment. $OUT should exist."
-    exit 1
+	echo -e $CL_RED"ERROR: $0 only works with a full build environment. $OUT should exist."$CL_RST
+	exit 1
 fi
 
 if [ "$TARGET_BUILD_TYPE" = "debug" ]; then
@@ -31,8 +33,8 @@ else
     OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$USER.zip
 fi
 if [ ! -f "$OTAPACKAGE" ]; then
-    echo "$OTAPACKAGE doesn't exist!";
-    exit 1
+	echo -e $CL_RED"$OTAPACKAGE doesn't exist!"$CL_RST;
+	exit 1
 fi
 
 OPTICHARGER=$ANDROID_BUILD_TOP/vendor/baked/tools/opticharger
@@ -160,6 +162,7 @@ rm -rf $REPACK/ota/recovery
 VERSION=`sed -n -e'/ro.baked.version/s/^.*=//p' $REPACK/ota/system/build.prop`
 MODVERSION="$VERSION"
 OUTFILE=$OUT/$MODVERSION.zip
+echo -e $CL BAKED "MODVERSION: $MODVERSION"$CL
 
 # Pack it up and sign
 printf "Zipping package..."
@@ -168,9 +171,9 @@ echo
 printf "Signing package..."
 SECURITYDIR=$ANDROID_BUILD_TOP/build/target/product/security
 java -Xmx1024m \
-    -jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar \
-    -w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
-    $REPACK/update.zip $OUTFILE
+	-jar $OUT/../../../host/$OUT_TARGET_HOST/framework/signapk.jar \
+	-w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
+	$REPACK/update.zip $OUTFILE
 echo
 printf "Cleaning up..."
 rm -rf $REPACK
@@ -182,7 +185,7 @@ img=`basename $OUTFILE`
 cd `dirname $OUTFILE`
 $MD5 $img >$img.md5sum
 echo
-echo "Package complete: $OUTFILE"
+echo -e $CL_GRN"Package complete: $OUTFILE"$CL_RST
 cat $img.md5sum
 echo
 )
